dtb-$(CONFIG_MACH_XIAOMI_VINCE) += ../../../../../../../../hardware/mititanium-module/kernel/dts/xiaomi-snow/vince-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_YSL) += ../../../../../../../../hardware/mititanium-module/kernel/dts/xiaomi-snow/ysl-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_MIDO) += ../../../../../../../../hardware/mititanium-module/kernel/dts/xiaomi-snow/mido-titanium.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo